### ISSUE TITLE
API unavailable?

### ISSUE THREAD

**Issue by espiegelberg** [Ruslanbek0809/Yummify#6]
Yummify looks like a promising project. I plan to study it to learn from.

Having cloned the code and (eventually) gotten it to run, the app launches but presents a blank view with the title of "Tables". Digging through the code, I believe the call to the API to retrieve data is failing.

The REST API (Backend Server, Storage), listed in the README.md with a url of http://185.223.93.215/login, is unavailable.

Can you please restore the URL so the app will function?

**Comment by Ruslanbek0809** [comment]
@espiegelberg Sorry for the late reply. 
If you are still interested, I can restore the URL and make the app work again. Feel free to open this issue again. I will close it for now.
