### ISSUE TITLE
Can't run with the latest version of Flutter

### ISSUE THREAD

**Issue by LofiYucef** [Ruslanbek0809/Yummify#7]
Hi, i tried to run this with the latest version of Flutter but i got too many errors.
here the version of Flutter i'm using

Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (6 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

can you please tell me which Version you used for this project, maybe if i downgraded Flutter i may have some success. Thank you for this awesome project.

**Comment by Ruslanbek0809** [comment]
Hello. I'm sorry for not getting back to you sooner. Use Flutter `2.x.x` versions. It is for sure not Flutter `3.24.3`.
